apiVersion: apps/v1
kind: Deployment
metadata:
  name: coretest-deployment
spec:
  selector:
    matchLabels:
      app: coretest-pod
  template:
    metadata:
      labels:
        app: coretest-pod
    spec:
      containers:
      - name: coretest-container
        image: lsoosai/coretest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
